FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["src/TextStream.Migrations/TextStream.Migrations.csproj", "src/TextStream.Migrations/"]
RUN dotnet restore "src/TextStream.Migrations/TextStream.Migrations.csproj"
COPY . .
WORKDIR "/src/src/TextStream.Migrations"
RUN dotnet build "TextStream.Migrations.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TextStream.Migrations.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TextStream.Migrations.dll"]
