version: '3.9'

volumes:
  volume1:
services:
  kafka1:
    image: 'bitnami/kafka:latest'
    container_name: kafka1
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
    volumes:
      - volume1:/bitnami/kafka
    networks:
      - dcs-bank
  ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka1:9092
      - KAFKA_CLUSTERS_0_NAME=kraft
    networks:
      - dcs-bank
  loans-applications-service-db:
    image: postgres:latest
    container_name: loans-applications-service-db
    ports:
      - "6432:5432"
    environment:
      POSTGRES_DB: "dcs"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    networks:
      - dcs-bank
  loans-applications-service-migration:
    build:
      context: ./Loans.Application
      dockerfile: Dockerfile-migration
    image: dcs-loans-applications-migration:latest
    container_name: loans-applications-migration
    depends_on:
      loans-applications-service-db:
        condition: service_healthy
    volumes:
      - ./loans-application/appsettings.json:/app/appsettings.json
    networks:
      - dcs-bank
  loans-applications-service:
    build:
      context: ./Loans.Application
      dockerfile: Dockerfile
    image: dcs-loans-applications:latest
    container_name: loans-applications
    ports:
      - "2023:80"
    depends_on:
      loans-applications-service-db:
        condition: service_healthy
      loans-applications-service-migration:
        condition: service_completed_successfully
    volumes:
      - ./loans-application/appsettings.json:/app/appsettings.json
      - ./Logs/:/app/Logs/
    networks:
      - dcs-bank
    environment:
      - Kafka__Servers__0=kafka1:9092
  api-gateway-service:
    networks:
      - dcs-bank
    depends_on:
      - loans-applications-service
    image: nickholas/dcs-api-gateway:latest
    volumes:
      - ./api-gateway-service/appsettings.json:/app/appsettings.json
    ports:
      - 2100:2100
  decision-maker-service-db:
    image: postgres:latest
    container_name: decision-maker-service-db
    ports:
     - "5432:5432"
    environment:
      POSTGRES_DB: "product_catalog"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "111111"
    networks:
     - dcs-bank
  decision-maker-service:
    restart: always
    image: nickholas/dcs-decision-maker-service:latest
    container_name: decision-maker-service
    ports:
      - "2001:80"
    depends_on: 
     - decision-maker-service-db
    volumes:
      - ./decision-maker-service/appsettings.json:/app/appsettings.json
    networks:
      - dcs-bank
    environment:
      - KafkaConfigurations__Servers=kafka1:9092
      - Kafka__ConsumerGroup=decision-maker-service-group
  emailing-service:
    networks:
      - dcs-bank
    image: nickholas/dcs-emailing-service:latest
    volumes:
      - ./emailing-service/appsettings.json:/app/appsettings.json
networks:
  dcs-bank:
    driver: bridge